### ISSUE TITLE
Enable flight connector

### ISSUE THREAD

**Issue by geyungjen** [dremio-hub/dremio-flight-connector#13]
In the github readme:

Enable Flight
the property -Ddremio.flight.enable=true MUST be set to enable flight
the property -Ddremio.flight.parallel.enable=true MUST be set on all executors to enable parallel flight

That did not enable flight connector, server.log shows below:

INFO  com.dremio.flight.FlightInitializer - Flight plugin is not enabled, skipping initialization

It should be:

Enable Flight
the property -Ddremio.flight.enabled=true MUST be set to enable flight
the property -Ddremio.flight.parallel.enabled=true MUST be set on all executors to enable parallel flight

Then flight connector starts, server.log show:

com.dremio.flight.FlightInitializer - set up flight plugin on port 47470 and host 0.0.0.0

Further:

./dremio-flight-connector/src/test/java/com/dremio/flight/TestSslFlightEndpoint.java:    System.setProperty("dremio.flight.enabled", "true");

./dremio-flight-connector/src/test/java/com/dremio/flight/TestFlightEndpoint.java:    System.setProperty("dremio.flight.parallel.enabled", "true"

**Comment by rymurr** [comment]
thanks @geyungjen  this type is now fixed
