### ISSUE TITLE
mvn clean install generates -SNAPSHOT .jar, not -shaded .jar

### ISSUE THREAD

**Issue by awaschick** [dremio-hub/dremio-flight-connector#24]
Please excuse the Java Noobie question.  

I am building the Flight Connector for Dremio 4.8 using the `maven:3.6.3-jdk-8`  docker container.  Previously, I had built this jar when using Dremio 4.3, and got the documented `dremio-flight-connector-{VERSION}-shaded.jar` result.  This time, with the same environment, running `mvn clean install` generates `dremio-flight-connector-0.26.0-SNAPSHOT.jar`... 

The build process _seems_ happy with this outcome, and in looking through the package, I see no specification referring to the `maven-shade` plugin.  I have not yet attempted to use this Jar as I'm building my own Dremio container image for use in my on-premise k8s cluster, but I'm inclined to give it a try.  

Will this `-SNAPSHOT` version crash in flames or is this simply a change in naming convention?  Or, is my build environment wrong where before it was acceptable?  Please advise.

**Comment by rymurr** [comment]
Hey @awaschick 

The `shaded` bit was from older instructions. We no longer produce the shaded jar and `{VERSION}` in the readme  is `0.26.0-SNAPSHOT`. I expect that the plugin should work fine.

Note that we create release binaries for each publicly released dremio verion https://github.com/dremio-hub/dremio-flight-connector/releases if you want to skip compiling yourself.

**Comment by awaschick** [comment]
Thanks @rymurr!  Confirmed, the build worked out fine.  Glad to know there are binaries to pull also!  Most appreciated and thanks for your contribution.
